In [1]:
import tensorflow as tf

In [2]:
mat = tf.constant([[12,23,34,45],[2,25,1,8],[5,7,78,12],[95,21,47,20]])
print(mat)

tf.Tensor(
[[12 23 34 45]
 [ 2 25  1  8]
 [ 5  7 78 12]
 [95 21 47 20]], shape=(4, 4), dtype=int32)


In [3]:
matmax = tf.math.reduce_max(mat,axis = 1)

In [4]:
matmax

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([45, 25, 78, 95])>

In [5]:
vtr1 = tf.constant([[2,5,1],[7,12,4],[19,15,6]])
vtr2 = tf.constant([[13,4,11],[67,23,45],[71,11,10]])
vtr3 = vtr1 + vtr2

In [6]:
vtr3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15,  9, 12],
       [74, 35, 49],
       [90, 26, 16]])>

In [7]:
vtr4 = tf.constant([[12,23],[34,45],[56,67]])
list1 = [[56,12],[34,15],[67,87]]
vtr5 = vtr4 + list1
vtr5

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 68,  35],
       [ 68,  60],
       [123, 154]])>